package com.group4.paladar.FireBaseLogic;

import com.firebase.client.DataSnapshot;
import com.firebase.client.Firebase;
import com.firebase.client.FirebaseError;
import com.firebase.client.ValueEventListener;
import com.group4.paladar.FireBaseStructures.event.DiningEvent;
import com.group4.paladar.FireBaseStructures.user.UserFirebase;

/**
 * Created by Alexander on 2016-03-07.
 */
public class DiningEventHandler {

    private static   Firebase mRef = new Firebase("https://paladar-android.firebaseio.com");

    public static String pushEventToServer(final DiningEvent event){

        Firebase newPostRef = mRef.child("events").push();

        newPostRef.setValue(event);
        // Get the unique ID generated by push()
        final String postId = newPostRef.getKey();

        //Firebase userRef = mRef.child("users").child(event.getHostId()).child("hostingIds").push();
        //userRef.setValue(postId);

                UserHelper.getUserInformation(event.getHostId(), new ValueEventListener() {
                    @Override
                    public void onDataChange(DataSnapshot dataSnapshot) {
                        UserFirebase user = dataSnapshot.getValue(UserFirebase.class);
                        user.getHostingIds().add(postId);
                        UserHelper.setUserInformation(event.getHostId(),user);
                    }

                    @Override
                    public void onCancelled(FirebaseError firebaseError) {}
                });

        return postId;
    }




}
